### PR TITLE
Remove dependency from default spec

### PR DESCRIPTION
**Pull request by RX14**
This allows power_assert.cr to be used with different Spec implementations like spec2.

### CODE REVIEW

**Comment by oprypin** [comment]
@RX14, this change causes a raw traceback to be printed in addition to the neat information.

```
  2) SF::Rect(T) contains? (vector)

         rect.contains?(SF.vector2(x, y)) == false 
         |    |            |       |  |   |
         |    |            |       |  |   false
         |    true         |       |  |
         |                 SF::Vector2(Int32)(@x=9, @y=9)
         |                         |  |
         |                         9  |
         |                            9
         SF::Rect(Int32)(@left=0, @top=0, @width=10, @height=10)
       [4552023] *CallStack::unwind:Array(Pointer(Void)) +87
       [4551914] *CallStack#initialize:Array(Pointer(Void)) +10
       [4551866] *CallStack::new:CallStack +42
       [4518120] *raise<PowerAssert::AssertionFailed>:NoReturn +24
       [4531061] ~procProc(Nil) +2645
       [4513933] *it<String, String, Int32, &Proc(Nil)>:(Array(Spec::Result) | Nil) +493
       [4525906] ~procProc(Nil) +1346
       [4657611] *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ +395
       [4513222] *describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ +6
       [4513198] ~procProc(Nil) +126
       [4657611] *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ +395
       [4513015] *describe<SF::Rect(T):Class, String, Int32, &Proc(Nil)>:Spec::Context+ +55
       [4444775] ???
       [4502025] main +41
       [140683198628497] __libc_start_main +241
       [4439562] _start +42
       [0] ???
```

**Comment by RX14** [comment]
Hmm, could we override the print stacktrace methods on Exception to not print the stacktrace?

**Comment by RX14** [comment]
Well, only `AssertionFailed` obviously.

**Comment by oprypin** [comment]
I should clarify: I'm using this in conjunction with "spec".

Another problem: it also changes the failure type from "F" to "E".

**Comment by RX14** [comment]
There's nothing much which can be done about that without having a standard "assertion failed" exception that all spec libraries use.

**Pull request merged**
